[package]
name = "easy-template"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", default-features = false, features = [
  "color",
  "error-context",
  "derive",
  "env",
  "help",
  "std",
  "suggestions",
  "usage",
] }
handlebars = { version = "6.3.2", default-features = false }
serde_json = { version = "1.0.140", default-features = false }
serde_yaml = { version = "0.9.34", default-features = false }
thiserror = { version = "2.0.12", default-features = false }
toml = { version = "0.8.23", default-features = false, features = ["parse"] }
